#!/bin/sh

# Homebrew Script for OSX
# To execute: save and `chmod +x ./brew-pkg-install.sh` then `./brew-pkg-install.sh`

echo "Installing brew..."
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo "Installing brew packages..."
brew tap "homebrew/bundle"
brew tap "zegervdv/zathura"
brew install "giflib"
brew install "jpeg-xl"
brew install "aom"
brew install "asciidoc"
brew install "chezmoi"
brew install "fzf"
brew install "gh"
brew install "git"
brew install "git-lfs"
brew install "openjdk"
brew install "gradle"
brew install "gtk+3"
brew install "gtk-mac-integration"
brew install "json-glib"
brew install "libavif"
brew install "libmagic"
brew install "libuv"
brew install "lpeg"
brew install "luajit"
brew install "macchina"
brew install "ninja"
brew install "msgpack"
brew install "tree-sitter"
brew install "unibilium"
brew install "neovim"
brew install "pipx"
brew install "ruby-build"
brew install "rbenv"
brew install "rename"
brew install "ripgrep"
brew install "sbcl"
brew install "sdl2"
brew install "sdl2_image"
brew install "sdl2_ttf"
brew install "tokei"
brew install "tree"
brew install "universal-ctags"
brew install "watchman"
brew install "zoxide"
brew install "zegervdv/zathura/zathura"
brew install "zegervdv/zathura/zathura-pdf-poppler"
brew install --cask "git-credential-manager"
brew install --cask "android-studio"
brew install --cask "visual-studio-code"
