#!/bin/sh

# Homebrew Script for OSX
# To execute: save and `chmod +x ./brew-pkg-install.sh` then `./brew-pkg-install.sh`

echo "Installing brew..."
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo "Installing brew packages..."
tap "homebrew/bundle"
brew "giflib"
brew "jpeg-xl"
brew "aom"
brew "asciidoc"
brew "fzf"
brew "gh"
brew "git"
brew "openjdk"
brew "gradle"
brew "hyfetch"
brew "libavif"
brew "libuv"
brew "lpeg"
brew "luajit"
brew "macchina"
brew "msgpack"
brew "tree-sitter"
brew "unibilium"
brew "neovim"
brew "podman"
brew "ruby-build"
brew "rbenv"
brew "rename"
brew "ripgrep"
brew "sbcl"
brew "sdl2"
brew "sdl2_image"
brew "sdl2_ttf"
brew "stow"
brew "tree"
brew "universal-ctags"
brew "zoxide"
cask "git-credential-manager"
