#!/bin/sh

# Homebrew Script for OSX
# To execute: save and `chmod +x ./brew-pkg-install.sh` then `./brew-pkg-install.sh`

echo "Installing brew..."
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew tap "felixkratz/formulae"
brew tap "homebrew/bundle"
brew tap "homebrew/services"
brew tap "koekeishiya/formulae"
brew tap "stripe/stripe-cli"
brew tap "zegervdv/zathura"
brew install "ca-certificates"
brew install "openssl@3"
brew install "giflib"
brew install "jpeg-xl"
brew install "aom"
brew install "asciidoc"
brew install "btop"
brew install "cbonsai"
brew install "chezmoi"
brew install "fzf"
brew install "gh"
brew install "git"
brew install "git-lfs"
brew install "openjdk"
brew install "gradle"
brew install "gtk+3"
brew install "gtk-mac-integration"
brew install "json-glib"
brew install "libavif"
brew install "libmagic"
brew install "libuv"
brew install "lpeg"
brew install "lua"
brew install "luajit"
brew install "macchina"
brew install "ninja"
brew install "msgpack"
brew install "tree-sitter"
brew install "unibilium"
brew install "neovim"
brew install "nowplaying-cli"
brew install "pandoc"
brew install "pipx"
brew install "ruby-build"
brew install "rbenv"
brew install "rename"
brew install "ripgrep"
brew install "sapling"
brew install "sbcl"
brew install "scipy"
brew install "sdl2"
brew install "sdl2_image"
brew install "sdl2_ttf"
brew install "spicetify-cli"
brew install "switchaudio-osx"
brew install "utf8proc", args: ["HEAD"]
brew install "tmux"
brew install "tokei"
brew install "tree"
brew install "universal-ctags"
brew install "watchman"
brew install "wget"
brew install "zoxide"
brew install "felixkratz/formulae/borders"
brew install "felixkratz/formulae/sketchybar"
brew install "koekeishiya/formulae/skhd"
brew install "koekeishiya/formulae/yabai"
brew install "stripe/stripe-cli/stripe"
brew install "zegervdv/zathura/zathura"
brew install "zegervdv/zathura/zathura-pdf-poppler"
brew install --cask "git-credential-manager"
brew install --cask "sf-symbols"
